# ================================
# ANACODE X ANTYLOGOUT
# Konfiguracja pluginu
# ================================

combat-time: 30

messages:
  actionbar: "&7Jesteś podczas walki jeszcze &4%time_left%"
  command-blocked: "&7Jesteś podczas walki nie możesz teraz tego &4użyć&7!"
  combat-start: "&cZostałeś oznaczony jako walczący!"
  combat-end: "&aNie jesteś już w trybie walki!"
  region-blocked: "&cNie możesz wejść na ten region podczas walki!"
  void-combat: "&cSpadasz w otchłań! Antylogout aktywny!"
  logout-death: "&c%player% &7wylogował się podczas walki i zginął!"
  logout-death-killer: "&c%player% &7wylogował się podczas walki i został zabity przez &c%killer%&7!"

allowed-commands:
  - "msg"
  - "r"
  - "reply"
  - "helpop"

blocked-regions:
  - "spawn"
  - "safezone"
  - "shop"

wall-distance: 10

wall:
  enabled: true
  width: 12
  height: 12
  material: RED_STAINED_GLASS
  corner-size: 2

kill-on-logout: true

void-combat:
  enabled: true
  worlds:
    - "world_the_end"
  below-y: -40
  show-message: true

last-damager:
  enabled: true
  memory-time: 60
  give-kill-on-logout: true
  broadcast-killer: true
  give-rewards: false
  reward-commands:
    - "eco give %killer% 100"
